### ISSUE TITLE
CandleLight, CANtact and CAN 2.0b messages

### ISSUE THREAD

**Issue by thorsteinssonh** [HubertD/candleLight_fw#11]
Dear Hubert,
I've been trying to interface with a CAN bus that uses the CAN 2.0b 29bit header format instead of the more typical CAB 2.0a 11bit format.
I'm trying to understand from docs or other if CANtact and CandleLight should be able to process these packets.  Could you give me some pointers if this hould work out of the box, or if I need to take any special steps.

Yours,
Hrob.

**Comment by HubertD** [comment]
Hi Hrobjartur,

it should be working out of the box, I'm using it on a regular basis.
candump should show you the extended frame ids, and you should be able to send them with cansend.

greetings,
Hubert
